// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbvipnqtfigvfmqotsaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNidmlwbnF0ZmlndmZtcW90c2FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NzY0NjAsImV4cCI6MjA3MTE1MjQ2MH0.CDrd1GRZdzU0OeE5fdlFChQoQ29rhDsBGiPk3wgQYdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});